import turtle as trtl
wn = trtl.Screen()

#Ask what branch of military
boat_image = "navy boat.gif"
navy_image = "navy.gif"
airforce_image = "air_force.gif"
jet_image = "jet.gif"
tank_image = "tank.gif"
army_image = "army.gif"
humvee_image = "humvee.gif"
marine_image = "marines.gif"
rocket_image = "rocket.gif"
space_image = "space_force.gif"
lighthouse_image = "lighthouse.gif"
coastguard_image = "coast_guard.gif"
writer = trtl.Turtle()
writer.hideturtle()

#envelope
def envelope(): 
    trtl.pensize(5)   
    trtl.color("black")
    trtl.speed(0)
    trtl.hideturtle()
    trtl.penup()
    trtl.goto(-200,100)
    trtl.pendown()
    for i in range(2):
        trtl.forward(400)
        trtl.right(90)
        trtl.forward(200)
        trtl.right(90)
    trtl.goto(0,0)
    trtl.goto(200,100)
    trtl.penup()
    trtl.goto(0,25)
    trtl.color("red")
    trtl.fillcolor("red")   
    trtl.pendown() 
    trtl.begin_fill()
    trtl.circle(-20)
    trtl.end_fill()

    trtl.penup()
    trtl.color("black")
    trtl.goto(-100,150)
    trtl.write("Click me!", font=("Arial", 45, "bold"))

#Show branch of military in background
def navy ():
    trtl.color("white")
    trtl.speed(0)
    trtl.pensize(6000)
    trtl.pendown()
    trtl.forward(200)
    envelope()
    def clear(x,y):
        wn.onclick(None)
        trtl.clear()
        wn.addshape(boat_image)
        boat = trtl.Turtle(shape=boat_image)
        wn.addshape(navy_image)
        navy_e = trtl.Turtle(shape=navy_image)
        navy_e.penup()
        navy_e.speed(0)
        navy_e.goto(200,200)
        writer.speed(0)
        writer.hideturtle()
        writer.penup()
        writer.goto(-400,300)
        writer.write("Thank you for your service!", font=("Arial", 45, "bold"))
        flag_creation()
    wn.onclick(clear)


def airforce():
    trtl.color("white")
    trtl.speed(0)
    trtl.pensize(6000)
    trtl.pendown()
    trtl.forward(600)
    envelope()
    def clear(x,y):
        wn.onclick(None)
        trtl.clear()
        wn.addshape(airforce_image)
        wn.addshape(jet_image)
        jet = trtl.Turtle(shape=jet_image)
        airforce_e = trtl.Turtle(shape=airforce_image)
        airforce_e.penup()
        airforce_e.speed(0)
        airforce_e.goto(200,200)
        writer.speed(0)
        writer.hideturtle()
        writer.penup()
        writer.goto(-400,300)
        writer.write("Thank you for your service!", font=("Arial", 45, "bold"))
        flag_creation()
    wn.onclick(clear)

def army():
    trtl.color("white")
    trtl.speed(0)
    trtl.pensize(6000)
    trtl.pendown()
    trtl.forward(200)
    envelope()
    def clear(x,y):
        wn.onclick(None)
        trtl.clear()
        wn.addshape(army_image)
        wn.addshape(tank_image)
        tank = trtl.Turtle(shape=tank_image)
        army_e = trtl.Turtle(shape=army_image)
        army_e.penup()
        army_e.speed(0)
        army_e.goto(200,200)
        writer.speed(0)
        writer.hideturtle()
        writer.penup()
        writer.goto(-400,300)
        writer.write("Thank you for your service!", font=("Arial", 45, "bold"))
        flag_creation()
    wn.onclick(clear)

def marine():
    trtl.color("white")
    trtl.speed(0)
    trtl.pensize(6000)
    trtl.pendown()
    trtl.forward(200)
    envelope()
    def clear(x,y):
        wn.onclick(None)
        trtl.clear()
        wn.addshape(marine_image)
        wn.addshape(humvee_image)
        humvee = trtl.Turtle(shape=humvee_image)
        marine_e = trtl.Turtle(shape=marine_image)
        marine_e.penup()
        marine_e.speed(0)
        marine_e.goto(200,200)
        writer.speed(0)
        writer.hideturtle()
        writer.penup()
        writer.goto(-400,300)
        writer.write("Thank you for your service!", font=("Arial", 45, "bold"))
        flag_creation()
    wn.onclick(clear)

def spaceforce():
    trtl.color("white")
    trtl.speed(0)
    trtl.pensize(6000)
    trtl.pendown()
    trtl.forward(200)
    envelope()
    def clear(x,y):
        wn.onclick(None)
        trtl.clear()
        wn.addshape(space_image)
        wn.addshape(rocket_image)
        rocket = trtl.Turtle(shape=rocket_image)
        space_e = trtl.Turtle(shape=space_image)
        space_e.penup()
        space_e.speed(0)
        space_e.goto(-200,200)
        writer.speed(0)
        writer.hideturtle()
        writer.penup()
        writer.goto(-400,300)
        writer.write("Thank you for your service!", font=("Arial", 45, "bold"))
        flag_creation()
    wn.onclick(clear)

def coastguard():
    trtl.color("white")
    trtl.speed(0)
    trtl.pensize(12000)
    trtl.pendown()
    trtl.forward(200)
    envelope()
    def clear(x,y):
        wn.onclick(None)
        trtl.clear()
        wn.addshape(coastguard_image)
        wn.addshape(lighthouse_image)
        lighthouse = trtl.Turtle(shape=lighthouse_image)
        coastguard_e = trtl.Turtle(shape=coastguard_image)
        coastguard_e.penup()
        coastguard_e.speed(0)
        coastguard_e.goto(200,200)
        writer.speed(0)
        writer.hideturtle()
        writer.penup()
        writer.goto(-400,300)
        writer.write("Thank you for your service!", font=("Arial", 45, "bold"))
        flag_creation()
    wn.onclick(clear)
    

branch_list = ["navy", "airforce","army","marine","spaceforce","coastguard"]

branch = trtl.textinput("Branch of Military","What Branch of Military Did You Serve In?(navy, airforce, army, marine, spaceforce, coastguard)")

while branch not in branch_list:
    branch = trtl.textinput("That isnt a branch(Typo?)","What Branch of Military Did You Serve In?(navy, airforce, army, marine, spaceforce, coastguard)")

if branch == branch_list[0]:
    navy()
if branch == branch_list[1]:
    airforce()
if branch == branch_list[2]:
    army()
if branch == branch_list[3]:
    marine()
if branch == branch_list[4]:
    spaceforce()
if branch == branch_list[5]:
    coastguard()

#Flag
def flag_creation():
    flag = trtl.Turtle()
    flag.penup()
    flag.goto(-150,-200)
    flag.pendown()
    flag.fillcolor("navyblue")
    flag.begin_fill()
    flag.speed(0)
    flag.forward(150)
    flag.right(90)
    flag.forward(80)
    flag.right(90)
    flag.forward(150)
    flag.right(90)
    flag.forward(80)
    flag.right(90)
    flag.end_fill()
    flag.forward(300)
    flag.right(90)

    trtl.addshape("star_shape",((0,-0.5),(-1,-2.5),(-3,-3),(-1,-4),(-2,-6),(0,-5),(2,-6),(1,-4),(3,-3),(1,-2.5)))
    star = trtl.Turtle(shape = "star_shape")
    star.speed(0)
    star.pencolor("white")
    star.fillcolor("white")
    star.penup()
    star.shapesize(2)
    x_cor = -130
    y_cor = -210
    for i in range(5):
        star.goto(x_cor,y_cor)
        star.stamp()
        star.forward(30)
        star.stamp()
        star.forward(30)
        star.stamp()
        star.forward(30)
        star.stamp()
        star.forward(30)
        star.stamp()
        star.forward(30)
        star.stamp()
        y_cor -= 15

    for i in range(3):
        flag.fillcolor("red")
        flag.begin_fill()
        flag.pencolor("red")
        flag.forward(11.5)
        flag.right(90)
        flag.forward(150)
        flag.right(90)
        flag.forward(11.5)
        flag.right(90)
        flag.forward(150)
        flag.right(90)
        flag.end_fill()
        flag.forward(11.5)
        flag.fillcolor("white")
        flag.begin_fill()
        flag.pencolor("white")
        flag.forward(11.5)
        flag.right(90)
        flag.forward(150)
        flag.right(90)
        flag.forward(11.5)
        flag.right(90)
        flag.forward(150)
        flag.right(90)
        flag.end_fill()
        flag.forward(11.5)
    flag.fillcolor("red")
    flag.begin_fill()
    flag.pencolor("red")
    flag.forward(11.5)
    flag.right(90)
    flag.forward(150)
    flag.right(90)
    flag.forward(11.5)
    flag.right(90)
    flag.forward(150)
    flag.right(90)
    flag.end_fill()
    flag.forward(11.5)
    for i in range(3):
        flag.fillcolor("white")
        flag.begin_fill()
        flag.pencolor("white")
        flag.forward(11.5)
        flag.right(90)
        flag.forward(300)
        flag.right(90)
        flag.forward(11.5)
        flag.right(90)
        flag.forward(300)
        flag.right(90)
        flag.end_fill()
        flag.forward(11.5)
        flag.fillcolor("red")
        flag.begin_fill()
        flag.pencolor("red")
        flag.forward(11.5)
        flag.right(90)
        flag.forward(300)
        flag.right(90)
        flag.forward(11.5)
        flag.right(90)
        flag.forward(300)
        flag.right(90)
        flag.end_fill()
        flag.forward(11.5)
    flag.fillcolor("white")
    flag.begin_fill()
    flag.pencolor("white")
    flag.forward(11.5)
    flag.right(90)
    flag.forward(300)
    flag.right(90)
    flag.forward(11.5)
    flag.right(90)
    flag.forward(300)
    flag.right(90)
    flag.end_fill()
    flag.forward(11.5)
    flag.right(90)

    flag.pencolor("black")
    for i in range (2):
        flag.forward(300)
        flag.right(90)
        flag.forward(162)
        flag.right(90)
    flag.forward(300)
    flag.right(90)

    flag.hideturtle()

wn.mainloop()